### ISSUE TITLE
Crash on Odyssey Startup

### ISSUE THREAD

**Issue by brnbrns** [poveden/EliteChroma#101]
## Summary

Since updating to Odyssey, EliteChroma crashes on startup when the Odyssey executable is running. I have set the game installation folder in the settings to the proper `odyssey` path. The app does not crash if Odyssey is not running. The error is the same each time:

Application: EliteChroma.exe
CoreCLR Version: 4.700.21.21202
.NET Core Version: 3.1.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteChroma.Core.LayerBase.ApplyColorToBinding(CustomKeyboardEffect grid, String bindingName, Color color) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\LayerBase.cs:line 116
   at EliteChroma.Core.LayerBase.ApplyColorToBinding(CustomKeyboardEffect grid, IEnumerable`1 bindingNames, Color color) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\LayerBase.cs:line 110
   at EliteChroma.Core.Layers.InterfaceModeLayer.OnRender(ChromaCanvas canvas) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Layers\InterfaceModeLayer.cs:line 24
   at EliteChroma.Core.LayerBase.OnRender(ChromaCanvas canvas, Object state) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\LayerBase.cs:line 44
   at EliteChroma.Chroma.LayeredEffect.Render(IChroma chroma, Object state) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Chroma\LayeredEffect.cs:line 38
   at EliteChroma.Core.ChromaController.RenderEffect() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\ChromaController.cs:line 247
   at EliteChroma.Core.ChromaController.GameState_Changed(Object sender, ChangeType e) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\ChromaController.cs:line 216
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

## Environment

- `EliteChroma` version: 1.11.0
- .NET Core version: 3.1.15
- Operating System: Windows 10 20H2

Thanks for all the great work on EliteChroma so far!

**Comment by poveden** [comment]
Thanks for your feedback and the error log!

I've pinpointed the issue: Odyssey divided the game controls screen into 4 sections _and_ added the ability to select different presets _per section_. EliteChroma expects only 1 active preset but it's getting 4, so it crashes.

The fix will take some time (mostly due to the all-new space legs bindings). Probably I'll push a hotfix so EliteChroma won't crash while I'm working on the final fix. Stay tuned!

**Comment by poveden** [comment]
[Version 1.12.0](https://github.com/poveden/EliteChroma/releases/tag/v1.12.0) is live! Please test it and let me know if it works for you.

**Comment by MadMousse** [comment]
> [Version 1.12.0](https://github.com/poveden/EliteChroma/releases/tag/v1.12.0) is live! Please test it and let me know if it works for you.

Hi !

I don't know if it's related, but 1.12.0 doesn't seems to startup for me (I don't have time to open Odyssey, Elite Chroma close before i even open the game.

Here is the log for me


Application: EliteChroma.exe
CoreCLR Version: 4.700.21.21202
.NET Core Version: 3.1.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException: There are multiple root elements. Line 4, position 6.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream)
   at EliteFiles.Graphics.GraphicsConfig.FromFile(String path) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\GraphicsConfig.cs:line 44
   at EliteFiles.Graphics.GraphicsConfigWatcher.<Reload>b__15_1() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\GraphicsConfigWatcher.cs:line 108
   at EliteFiles.Internal.FileOperations.RetryIfNull[T](Func`1 action, Int32 retries) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\FileOperations.cs:line 11
   at EliteFiles.Graphics.GraphicsConfigWatcher.Reload() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\GraphicsConfigWatcher.cs:line 107
   at EliteFiles.Graphics.GraphicsConfigWatcher.Start() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\GraphicsConfigWatcher.cs:line 60
   at EliteChroma.Elite.GameStateWatcher.Start() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Elite\GameStateWatcher.cs:line 98
   at EliteChroma.Core.ChromaController.Start() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\ChromaController.cs:line 103
   at EliteChroma.AppContext.CycleChromaController(AppSettings settings) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\AppContext.cs:line 146
   at EliteChroma.AppContext.Start() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\AppContext.cs:line 67
   at EliteChroma.Program.Main() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\Program.cs:line 38

**Comment by brnbrns** [comment]
1.12.0 is working well for me!

Thanks for the quick fix.

**Comment by poveden** [comment]
> I don't know if it's related, but 1.12.0 doesn't seems to startup for me (I don't have time to open Odyssey, Elite Chroma close before i even open the game.

@MadMousse no, it shouldn't be related to this release. Your error points to a malformed `GraphicsConfigurationOverride.xml` file. Specifically:

> `There are multiple root elements. Line 4, position 6.`

I'm guessing that you edited that file directly, or via a tool to customize your HUD colors. Just fix that file (usually located in the `` folder), and you should be good to go.

This crash reason is very common (I'm tracking it on #67). When I get some time I will make EliteChroma more resistant to such files.
