### ISSUE TITLE
Maelstrom systems causing app to crash due to missing entry

### ISSUE THREAD

**Issue by pr1sm47** [poveden/EliteChroma#163]
Entering a system where a titan is present causes the app to crash at a random interval followed by almost succesive crashes on reloading the app.

## Steps to Reproduce

enter a maelstrom system in game, the lighting effects flash randomly (simulating the effect the thargoids have on the cockpit hud?) soon after the app will crash.

## Expected Behavior

app should continue as normal.

## Environment

- `EliteChroma` version: 1.18.0
- .NET Core version:  6.0.2123.36311
- Operating System:  Win10
## Additional Context

Log Name:      Application
Source:        .NET Runtime
Date:          12/08/2023 04:49:03
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      PC
Description:
Application: EliteChroma.exe
CoreCLR Version: 6.0.2123.36311
.NET Version: 6.0.21
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException: The given key 'Titan_Encounter' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EliteFiles.Internal.JsonStringEnumNameConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\JsonStringEnumNameConverter.cs:line 17
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadDocument[TValue](JsonDocument document, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(JsonDocument document, Type returnType, JsonSerializerContext context)
   at EliteFiles.Journal.Internal.JournalEntryConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\Internal\JournalEntryConverter.cs:line 31
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo)
   at EliteFiles.Journal.JournalReader.TryReadEntryFromBuffer(JournalEntry& entry) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\JournalReader.cs:line 91
   at EliteFiles.Journal.JournalReader.ReadEntry() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\JournalReader.cs:line 72
   at EliteFiles.Journal.JournalWatcher.DispatchEventsFromJournal() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\JournalWatcher.cs:line 161
   at EliteFiles.Journal.JournalWatcher.JournalFilesWatcher_Changed(Object sender, FileSystemEventArgs e) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\JournalWatcher.cs:line 131
   at EliteFiles.Internal.EliteFileSystemWatcher.OnChanged(FileSystemEventArgs e) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\EliteFileSystemWatcher.cs:line 123
   at EliteFiles.Internal.EliteFileSystemWatcher.Watcher_Changed(Object sender, FileSystemEventArgs e) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\EliteFileSystemWatcher.cs:line 105
   at System.IO.FileSystemWatcher.InvokeOn(FileSystemEventArgs e, FileSystemEventHandler handler)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(ReadOnlySpan`1 buffer)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__83_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-08-12T03:49:03.3891863Z" />
    <EventRecordID>134984</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: EliteChroma.exe
CoreCLR Version: 6.0.2123.36311
.NET Version: 6.0.21
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException: The given key 'Titan_Encounter' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EliteFiles.Internal.JsonStringEnumNameConverter`1.Read(Utf8JsonReader&amp; reader, Type typeToConvert, JsonSerializerOptions options) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\JsonStringEnumNameConverter.cs:line 17
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&amp; reader, Type typeToConvert, JsonSerializerOptions options, ReadStack&amp; state, T&amp; value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack&amp; state, Utf8JsonReader&amp; reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&amp; reader, Type typeToConvert, JsonSerializerOptions options, ReadStack&amp; state, T&amp; value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&amp; reader, Type typeToConvert, JsonSerializerOptions options, ReadStack&amp; state, T&amp; value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&amp; reader, JsonSerializerOptions options, ReadStack&amp; state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader&amp; reader, JsonSerializerOptions options, ReadStack&amp; state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadDocument[TValue](JsonDocument document, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(JsonDocument document, Type returnType, JsonSerializerContext context)
   at EliteFiles.Journal.Internal.JournalEntryConverter.Read(Utf8JsonReader&amp; reader, Type typeToConvert, JsonSerializerOptions options) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\Internal\JournalEntryConverter.cs:line 31
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&amp; reader, Type typeToConvert, JsonSerializerOptions options, ReadStack&amp; state, T&amp; value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&amp; reader, JsonSerializerOptions options, ReadStack&amp; state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo)
   at EliteFiles.Journal.JournalReader.TryReadEntryFromBuffer(JournalEntry&amp; entry) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\JournalReader.cs:line 91
   at EliteFiles.Journal.JournalReader.ReadEntry() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\JournalReader.cs:line 72
   at EliteFiles.Journal.JournalWatcher.DispatchEventsFromJournal() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\JournalWatcher.cs:line 161
   at EliteFiles.Journal.JournalWatcher.JournalFilesWatcher_Changed(Object sender, FileSystemEventArgs e) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Journal\JournalWatcher.cs:line 131
   at EliteFiles.Internal.EliteFileSystemWatcher.OnChanged(FileSystemEventArgs e) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\EliteFileSystemWatcher.cs:line 123
   at EliteFiles.Internal.EliteFileSystemWatcher.Watcher_Changed(Object sender, FileSystemEventArgs e) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\EliteFileSystemWatcher.cs:line 105
   at System.IO.FileSystemWatcher.InvokeOn(FileSystemEventArgs e, FileSystemEventHandler handler)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(ReadOnlySpan`1 buffer)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.&lt;&gt;c.&lt;StartRaisingEvents&gt;b__83_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
</Data>
  </EventData>
</Event>

**Comment by pr1sm47** [comment]
Hi Jordi, apologies this email got spam filtered so i have only just come across your reply.

I've attached the full log for the session minus fid's of course in case any of the other journal entries help in any way.








On Tuesday, 15 August 2023 at 15:03:48 BST, Jordi Poveda ***@***.***> wrote: 







Thanks for reporting this. Could you please share with me a sample of your journal where Titan_Encounter can be found, so I can reproduce the issue?

**Comment by poveden** [comment]
It looks that your attachment didn't came through. Can you try again?

**Comment by pr1sm47** [comment]
Of course






On Friday, 29 September 2023 at 23:00:16 BST, Jordi Poveda ***@***.***> wrote: 







It looks that your attachment didn't came through. Can you try again?

**Comment by poveden** [comment]
It looks like you're trying to send the file via email. Apparently email attachments won't pass through. Could you please attach it directly in the issue?

**Comment by pr1sm47** [comment]
[Journal.2023-08-14T213738.01.log](https://github.com/poveden/EliteChroma/files/12775257/Journal.2023-08-14T213738.01.log)
This should work

**Comment by poveden** [comment]
I've just released [version 1.18.1](https://github.com/poveden/EliteChroma/releases/tag/v1.18.1) with a fix. Please let me know how it goes.
