### ISSUE TITLE
EliteChroma crashing since Ascendancy update

### ISSUE THREAD

**Issue by r4z0rw1r3** [poveden/EliteChroma#169]
## Summary

App works ok until I join the server, as soon as I'm at cockpit view, EliteChroma app crashes and won't restart until I quit game to desktop.  Was all working fine the day before the Ascendancy update on 31st October 2024.  

## Steps to Reproduce

1. Start Game (usual EliteChroma 'yellow' glow starts as expected)
2. At game menu, select 'continue'
3. I select 'Private Group Session' at this point.
4. Game loads to cockpit view
5. EliteChroma app crashes at this point.  
6. Alt-tab to desktop and try and reload EliteChroma app, won't restart (until I fully exit game to desktop)

## Expected Behaviour

At cockpit I am usually docked / landing gear down, so expected most lighting to go 'deep blue' - instead, app crashes and lighting reverts back to my default razer desktop profile

## Environment

![image](https://github.com/user-attachments/assets/a611f0da-80bb-4b4a-baba-4070e7dbcbb6)

![image](https://github.com/user-attachments/assets/6fb4ae20-d4c2-4bb9-aba1-8f10176a0dba)

![image](https://github.com/user-attachments/assets/0de64e2a-a26f-4e28-a83b-e8160585b73e)

2 related crash events in Windows event viewer:

![image](https://github.com/user-attachments/assets/4a735293-4623-4229-abe4-5e0c31c68c9b)

Application: EliteChroma.exe
CoreCLR Version: 6.0.3524.45918
.NET Version: 6.0.35
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Text.Json.JsonException: The JSON value could not be converted to EliteFiles.Status.LegalState. Path: $.LegalState | LineNumber: 0 | BytePositionInLine: 230.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadAsPropertyNameCore(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAll[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream utf8Json, JsonTypeInfo`1 jsonTypeInfo)
   at EliteFiles.Status.StatusEntry.FromFile(String path) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Status\StatusEntry.cs:line 183
   at EliteFiles.Status.StatusWatcher.<Reload>b__13_0() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Status\StatusWatcher.cs:line 88
   at EliteFiles.Internal.FileOperations.RetryIfFailed[T](Func`1 action, Func`2 test, Int32 retries) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\FileOperations.cs:line 13
   at EliteFiles.Internal.FileOperations.RetryIfNull[T](Func`1 action, Int32 retries) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\FileOperations.cs:line 8
   at EliteFiles.Status.StatusWatcher.Reload() in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Status\StatusWatcher.cs:line 87
   at EliteFiles.Status.StatusWatcher.StatusWatcher_Changed(Object sender, FileSystemEventArgs e) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Status\StatusWatcher.cs:line 82
   at EliteFiles.Internal.EliteFileSystemWatcher.OnChanged(FileSystemEventArgs e) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\EliteFileSystemWatcher.cs:line 123
   at EliteFiles.Internal.EliteFileSystemWatcher.Watcher_Changed(Object sender, FileSystemEventArgs e) in C:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\EliteFileSystemWatcher.cs:line 105
   at System.IO.FileSystemWatcher.InvokeOn(FileSystemEventArgs e, FileSystemEventHandler handler)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(ReadOnlySpan`1 buffer)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__83_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

![image](https://github.com/user-attachments/assets/119ec79d-2046-461f-97a2-c7832cf27d60)

Faulting application name: EliteChroma.exe, version: 1.18.2.0, time stamp: 0x656f0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4391, time stamp: 0x7433a115
Exception code: 0xe0434352
Fault offset: 0x000000000005fa4c
Faulting process id: 0x0x49F0
Faulting application start time: 0x0x1DB2C6BC5C67A89
Faulting application path: C:\Program Files\EliteChroma\EliteChroma.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8efc8978-41a8-44d6-9542-06b5ec83950a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by GrasshopperMan17** [comment]
im getting the same exact thing, with the same info

**Comment by r4z0rw1r3** [comment]
Update - Seems to be something to do with being docked / landing gear down, when the lighting goes 'deep blue'.

I logged out of game mid-space today (in analysis mode), when I logged back in, Elite Chroma didn't crash and just gave the usual 'light blue' lighting from being in-flight / analysis mode.  The lighting reacted 'orange' from a switch to combat mode.

Continued to work fine until I next landed at a station, then as soon as the docking procedure started (when you get 'deep blue' lighting), app crashed again as described above.

**Comment by GrasshopperMan17** [comment]
its not though. i logged out near a res site with my landing gear up and in combat mode, and as soon as i loaded into my cockpit EC crashed

**Comment by DonChooluvit** [comment]
Confirmed on my end too. However, it was crashing while I was flying a Mandalay. Today I swapped to an Anaconda and the app worked as expected

**Comment by r4z0rw1r3** [comment]
> Confirmed on my end too. However, it was crashing while I was flying a Mandalay. Today I swapped to an Anaconda and the app worked as expected

Hadn't considered that, I've been using the Mandalay since the Ascendancy release, so I will try changing ship too.

**Comment by Falcon911** [comment]
Damn was hoping that would have worked.

**Comment by Falcon911** [comment]
@poveden Any ideas or you stumped?

**Comment by poveden** [comment]
@Falcon911 Sorry for the delay. I've been very busy at work, and now I'm on holidays... which is a different kind of "busy". 😅

@r4z0rw1r3 According to your stack trace, the error occurs because your legal status is not a recognized one by EliteChroma. Could you please (or @GrasshopperMan17, or @DonChooluvit) try to reproduce the issue and, just when it happens, capture the contents of the `Status.json` file (located at `%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous`)?

**Comment by Falcon911** [comment]
{ "timestamp":"2024-12-24T03:51:30Z", "event":"Status", "Flags":151060493, "Flags2":0, "Pips":[2,8,2], "FireGroup":0, "GuiFocus":0, "Fuel":{ "FuelMain":32.000000, "FuelReservoir":1.130000 }, "Cargo":0.000000, "LegalState":"Allied", "Balance":10016267931 }

**Comment by r4z0rw1r3** [comment]
{ "timestamp":"2024-12-25T14:52:03Z", "event":"Status", "Flags":151060493, "Flags2":0, "Pips":[2,8,2], "FireGroup":1, "GuiFocus":0, "Fuel":{ "FuelMain":32.000000, "FuelReservoir":0.520000 }, "Cargo":0.000000, "LegalState":"Allied", "Balance":216691998 }

Merry Christmas!

**Comment by poveden** [comment]
Just uploaded [version 1.18.3](https://github.com/poveden/EliteChroma/releases/tag/v1.18.3) with the fix. Please let me know how it works out for you.

Happy Holidays!

**Comment by Falcon911** [comment]
one more sir
{ "timestamp":"2024-12-28T16:33:25Z", "event":"Status", "Flags":306708680, "Flags2":0, "Pips":[2,2,8], "FireGroup":0, "GuiFocus":0, "Fuel":{ "FuelMain":0.000000, "FuelReservoir":0.240000 }, "Cargo":0.000000, "LegalState":"Contested", "Balance":10058611239 }

**Comment by Falcon911** [comment]
Need to jump over to a unoccupied system one to see if that changes too so hang on a sec

**Comment by Falcon911** [comment]
{ "timestamp":"2024-12-28T17:14:13Z", "event":"Status", "Flags":285212824, "Flags2":0, "Pips":[2,8,2], "FireGroup":1, "GuiFocus":0, "Fuel":{ "FuelMain":29.686169, "FuelReservoir":0.134944 }, "Cargo":0.000000, "LegalState":"Clean", "Balance":10058611239 }
Unoccupied no change.,

**Comment by poveden** [comment]
There, [version 1.18.4](https://github.com/poveden/EliteChroma/releases/tag/v1.18.4) is out. Hopefully everything's OK now. 😅
