### ISSUE TITLE
Elite Chroma not Starting

### ISSUE THREAD

**Issue by acidgen** [poveden/EliteChroma#66]
Hi
Elite Chroma Crashes on launch.
Have the following connected to the Razer Chroma
1x Led Strip - Hue
1x Led Bloom light
16x Nano Leaf

Crashlog Windows:
Faulting application name: EliteChroma.exe, version: 1.9.0.0, time stamp: 0x5f6b3998
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1139, time stamp: 0xa8b891f5
Exception code: 0xe0434352
Fault offset: 0x0000000000043b29
Faulting process id: 0x6b74
Faulting application start time: 0x01d6b5d213cf0600
Faulting application path: C:\Program Files\EliteChroma\EliteChroma.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 07103190-5fdf-45c4-9aff-170e2e5ce70f
Faulting package full name: 
Faulting package-relative application ID: 

Crashlog Elite Chroma:
Application: EliteChroma.exe
CoreCLR Version: 4.700.20.41105
.NET Core Version: 3.1.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: GraphicsConfig. Line 12, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream)
   at EliteFiles.Graphics.GraphicsConfig.FromFile(String path) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\GraphicsConfig.cs:line 44
   at EliteFiles.Graphics.GraphicsConfigWatcher.<Reload>b__15_1() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\GraphicsConfigWatcher.cs:line 108
   at EliteFiles.Internal.FileOperations.RetryIfNull[T](Func`1 action, Int32 retries) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Internal\FileOperations.cs:line 11
   at EliteFiles.Graphics.GraphicsConfigWatcher.Reload() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\GraphicsConfigWatcher.cs:line 107
   at EliteFiles.Graphics.GraphicsConfigWatcher.Start() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteFiles\Graphics\GraphicsConfigWatcher.cs:line 60
   at EliteChroma.Elite.GameStateWatcher.Start() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Elite\GameStateWatcher.cs:line 98
   at EliteChroma.Core.ChromaController.Start() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\ChromaController.cs:line 99
   at EliteChroma.AppContext.CycleChromaController(AppSettings settings) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\AppContext.cs:line 133
   at EliteChroma.AppContext.Start() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\AppContext.cs:line 66
   at EliteChroma.Program.Main() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma\Program.cs:line 38

**Comment by poveden** [comment]
@acidgen It looks like your `GraphicsConfigurationOverride.xml` is broken. Can you share it here, please? You should be able to find it in the `%LOCALAPPDATA%\Frontier Developments\Elite Dangerous\Options\Graphics` folder.

**Comment by acidgen** [comment]
<?xml version="1.0" encoding="UTF-8" ?>
<GraphicsConfig>
<GUIColour>
  <Default>
    <LocalisationName>Standard</LocalisationName>
   <MatrixRed> 0.05, 0.25, 0.60 </MatrixRed>
<MatrixGreen> 0, 1, 0 </MatrixGreen>
<MatrixBlue> 1, 0, 0 </MatrixBlue>
  </Default>
</GUIColour>
<GraphicsConfig />

**Comment by acidgen** [comment]
```
<?xml version="1.0" encoding="UTF-8" ?>
<GraphicsConfig>
<GUIColour>
  <Default>
    <LocalisationName>Standard</LocalisationName>
   <MatrixRed> 0.05, 0.25, 0.60 </MatrixRed>
<MatrixGreen> 0, 1, 0 </MatrixGreen>
<MatrixBlue> 1, 0, 0 </MatrixBlue>
  </Default>
</GUIColour>
<GraphicsConfig />

```

**Comment by acidgen** [comment]
See that the slash might be wrong, gonna check and try.

**Comment by acidgen** [comment]
Works now, used an auto-tool earlier to change hud colors, others getting the same problem might have used the same online tool. FYI, it works and you can close the Issue. Thanks

**Comment by poveden** [comment]
Thank you for reporting this, @acidgen. I'll add some checks so EliteChroma won't crash on that kind of files.
