### ISSUE TITLE
Silent Crashing on Steam Startup

### ISSUE THREAD

**Issue by NotDented** [poveden/EliteChroma#74]
I'm using EliteChroma version 1.9.1.  Everything appeared to install correctly.  I start up EliteChroma without issues.  Once I enter the game, my lights flicker and then revert to their default settings.  I do not get an error message.

I run the game through Steam.  File setup is as follows:
Game installation folder: C:\SteamLibrary\steamapps\common\Elite Dangerous\Products\elite-dangerous-64
Game options folder: C:\Users\NotDented\AppData\Local\Frontier Developments\Elite Dangerous\Options
Journal folder: C:\Users\NotDented\Saved Games\Frontier Developments\Elite Dangerous

I use a Huntsman Elite keyboard, a Goliathus pad, a Deathadder V2, and Lifx bulbs connected via the Chroma Connector.  I'm running Synapse 3.

**Comment by poveden** [comment]
Hi @NotDented! Thanks for reporting this. Could you please check the Windows Application Event Log just after EliteChroma closes? Look for error entries with .NET Runtime as the event source.

**Comment by NotDented** [comment]
Error - .NET Runtime
Application: EliteChroma.exe
CoreCLR Version: 4.700.20.51601
.NET Core Version: 3.1.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at EliteChroma.Core.Internal.OemKeyMappings.TryGetKey(String keyboardLayout, Char c, Boolean enUSOverride, VirtualKey& key, INativeMethods nativeMethods) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Internal\OemKeyMappings.cs:line 51
   at EliteChroma.Elite.Internal.KeyMappings.TryGetKey(String keyName, String keyboardLayout, Boolean enUSOverride, VirtualKey& key, INativeMethods nativeMethods) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Elite\Internal\KeyMappings.cs:line 174
   at EliteChroma.Core.Internal.KeyMappings.TryGetKey(String keyName, String keyboardLayout, Boolean enUSOverride, Key& key, INativeMethods nativeMethods) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Internal\KeyMappings.cs:line 194
   at EliteChroma.Core.LayerBase.ApplyColorToBinding(CustomKeyboardEffect grid, String bindingName, Color color) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\LayerBase.cs:line 121
   at EliteChroma.Core.LayerBase.ApplyColorToBinding(CustomKeyboardEffect grid, IEnumerable`1 bindingNames, Color color) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\LayerBase.cs:line 108
   at EliteChroma.Core.Layers.InterfaceModeLayer.OnRender(ChromaCanvas canvas) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Layers\InterfaceModeLayer.cs:line 25
   at EliteChroma.Core.LayerBase.OnRender(ChromaCanvas canvas, Object state) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\LayerBase.cs:line 45
   at EliteChroma.Chroma.LayeredEffect.Render(IChroma chroma, Object state) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\Chroma\LayeredEffect.cs:line 36
   at EliteChroma.Core.ChromaController.RenderEffect() in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\ChromaController.cs:line 238
   at EliteChroma.Core.ChromaController.GameState_Changed(Object sender, ChangeType e) in D:\Dev\GitHub\poveden\EliteChroma\src\EliteChroma.Core\ChromaController.cs:line 207
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Error - Application Error
Faulting application name: EliteChroma.exe, version: 1.9.1.0, time stamp: 0x5f6b3998
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0x6f5c
Faulting application start time: 0x01d6c820cd63c24e
Faulting application path: C:\Program Files\EliteChroma\EliteChroma.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: ca727be7-007a-4139-8d6f-3ff5e669df44
Faulting package full name: 
Faulting package-relative application ID:

**Comment by poveden** [comment]
@NotDented I've pinpointed the issue. It seems that you are using a pre-configured keyboard bindings option instead of a custom one.  EliteChroma uses the custom file to get the keyboard layout, but such layout is missing from the pre-configured ones.

I'll write a fix for this and push an update as soon as I can. I'll let you know when it's done.

**Comment by poveden** [comment]
[Version 1.9.2](https://github.com/poveden/EliteChroma/releases/tag/v1.9.2) has been published.

@NotDented please test it and tell me how it goes.

**Comment by NotDented** [comment]
Looks like you fixed it.  All my devices are changing colors nicely.

I appreciate you working on this.  Thank you!
